name: Update index
on:
  # When I say so.
  workflow_dispatch:

  # Every MORNING at 8:40 AM UTC (~ 2:40AM central)
  schedule:
    # https://crontab.guru/#40_8_*_*_*
    - cron: 40 8 * * *

  # Run when the settings file is modified on `main` branch.
  push:
    paths:
      - "settings.json"
    branches: [main]

env:
  TARGET: ${{ github.event.client_payload.target || github.event.inputs.target }}
  TEAM: storytelling-studio
  CAST_PROJECT: ${{ github.event.client_payload.app || github.event.inputs.app }}
  CDN_AUTH: ${{ secrets.CDN_AUTH }}
  USAT_AUTH: ${{ secrets.USAT_AUTH }}
  USCP_AUTH: ${{ secrets.USCP_AUTH }}
  GAPI_CLIENT_EMAIL: ${{ secrets.GAPI_CLIENT_EMAIL }}
  GAPI_PRIVATE_KEY: ${{ secrets.GAPI_PRIVATE_KEY }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GCP_SA_KEY_B64: ${{ secrets.GCP_SA_KEY_B64 }}

defaults:
  run:
    shell: bash

jobs:
  publish:
    # The type of runner that the job will run on
    runs-on: [self-hosted, cloud-engineering, tools-low]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Configure Vault Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.1.0
        with:
          url: https://vault.gannettdigital.com
          method: approle
          roleId: ${{ secrets.VAULT_APPROLE_ROLEID }}
          secretId: ${{ secrets.VAULT_APPROLE_SECRETID }}
          secrets: |
            secret/storytelling-studio/storytelling-studio-apps GAPI_CLIENT_EMAIL;
            secret/storytelling-studio/storytelling-studio-apps GAPI_PRIVATE_KEY;
            secret/storytelling-studio/storytelling-studio-apps GCP_PROJECT_ID;
            secret/storytelling-studio/storytelling-studio-apps GCP_SA_KEY;
            secret/storytelling-studio/storytelling-studio-apps GCP_SA_KEY_B64;
            secret/storytelling-studio/storytelling-studio-apps CDN_AUTH;
            secret/storytelling-studio/storytelling-studio-apps USAT_AUTH;
            secret/storytelling-studio/storytelling-studio-apps USCP_AUTH;
            secret/storytelling-studio/lab-microservices CONTENT_API_KEY;
            secret/storytelling-studio/storytelling-studio-apps MAPBOX_ACCESS_TOKEN;

      # AUTHORIZE GCLOUD HERE
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ env.GCP_SA_KEY_B64 }}

      # configure gcloud and gsutil
      - name: GCloud setup
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      # Add authentication for github packages
      - name: Github packages
        run: echo //npm.pkg.github.com/:_authToken=${{ secrets.PRIVATE_ACTION_TOKEN }} >> ~/.npmrc

      # install dependencies
      - name: install
        run: make install

      - name: Update index
        if: ${{ env.CAST_PROJECT != 'cast-of-characters-index' }}
        run: |
          # Update spreadsheet for index
          node functions/cast-index.js

          # Trigger a preprod publish
          curl --location --request POST 'https://us-central1-gannett-storytelling-dev.cloudfunctions.net/castProxy' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "event_type": "publish-app",
                "client_payload": {
                    "app": "cast-of-characters-index",
                    "target": "preprod"
                }
            }'
